# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(708, 486)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 720, 80))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.label.setObjectName("label")
        self.rvalue = QtWidgets.QPushButton(Form)
        self.rvalue.setGeometry(QtCore.QRect(0, 80, 350, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.rvalue.setFont(font)
        self.rvalue.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(100, 178, 102, 255), stop:0.55 rgba(235, 180, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.rvalue.setObjectName("rvalue")
        self.gvalue = QtWidgets.QPushButton(Form)
        self.gvalue.setGeometry(QtCore.QRect(350, 180, 350, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.gvalue.setFont(font)
        self.gvalue.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(100, 178, 102, 255), stop:0.55 rgba(235, 180, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
            "")
        self.gvalue.setObjectName("gvalue")
        self.pivalue = QtWidgets.QPushButton(Form)
        self.pivalue.setGeometry(QtCore.QRect(0, 180, 350, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pivalue.setFont(font)
        self.pivalue.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(100, 178, 102, 255), stop:0.55 rgba(235, 180, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.pivalue.setObjectName("pivalue")
        self.cvalue = QtWidgets.QPushButton(Form)
        self.cvalue.setGeometry(QtCore.QRect(350, 80, 350, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cvalue.setFont(font)
        self.cvalue.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(100, 178, 102, 255), stop:0.55 rgba(235, 180, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.cvalue.setObjectName("cvalue")
        self.qvalue = QtWidgets.QPushButton(Form)
        self.qvalue.setGeometry(QtCore.QRect(350, 280, 350, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.qvalue.setFont(font)
        self.qvalue.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(100, 178, 102, 255), stop:0.55 rgba(235, 180, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.qvalue.setObjectName("qvalue")
        self.pvalue = QtWidgets.QPushButton(Form)
        self.pvalue.setGeometry(QtCore.QRect(350, 380, 350, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pvalue.setFont(font)
        self.pvalue.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(100, 178, 102, 255), stop:0.55 rgba(235, 180, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.pvalue.setObjectName("pvalue")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 380, 350, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(100, 178, 102, 255), stop:0.55 rgba(235, 180, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
            "")
        self.pushButton_14.setObjectName("pushButton_14")
        self.expvalue = QtWidgets.QPushButton(Form)
        self.expvalue.setGeometry(QtCore.QRect(0, 280, 350, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.expvalue.setFont(font)
        self.expvalue.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(100, 178, 102, 255), stop:0.55 rgba(235, 180, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.expvalue.setObjectName("expvalue")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Константы"))
        self.rvalue.setText(_translate("Form", "R = 8.31"))
        self.gvalue.setText(_translate("Form", "G = 6.67*10^-11"))
        self.pivalue.setText(_translate("Form", "pi = 3.14"))
        self.cvalue.setText(_translate("Form", "c = 3 * 10^8"))
        self.qvalue.setText(_translate("Form", "q = 1.67 * 10^-19"))
        self.pvalue.setText(_translate("Form", "P = 101 325 "))
        self.pushButton_14.setText(_translate("Form", "k= 1.38*10^-23"))
        self.expvalue.setText(_translate("Form", "e = 2.71"))

    def add_functions(self, classname):
        self.rvalue.clicked.connect(lambda: classname.write_number("8.31"))
        self.pivalue.clicked.connect(lambda: classname.write_number("3.14"))
        self.expvalue.clicked.connect(lambda: classname.write_number("2.71"))
        self.pushButton_14.clicked.connect(lambda: classname.write_number("1.38*10**(-23)"))
        self.cvalue.clicked.connect(lambda: classname.write_number("3*10**8"))
        self.gvalue.clicked.connect(lambda: classname.write_number("6.67*10**(-11)"))
        self.qvalue.clicked.connect(lambda: classname.write_number("1.67*10**(-19)"))
        self.pvalue.clicked.connect(lambda: classname.write_number("101325"))